# Generated by Django 3.1 on 2021-01-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PID_db',
            fields=[
                ('sim_time', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Tau', models.BinaryField()),
                ('Q_prim', models.BinaryField()),
                ('Kat', models.BinaryField()),
                ('E', models.BinaryField()),
                ('t', models.FloatField()),
            ],
        ),
    ]
