# Generated by Django 3.1.5 on 2021-02-11 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_auto_20210120_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='FUZZY_db',
            fields=[
                ('sim_time', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Tau', models.BinaryField()),
                ('Kat', models.BinaryField()),
                ('E', models.BinaryField()),
                ('t', models.FloatField(default=1)),
                ('n', models.IntegerField(default=1)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.pid_db')),
            ],
        ),
    ]
